### PR TITLE
fix: use custom preview page (preview.vue) if exists

### PR DESCRIPTION
**Pull request by tosbatti**
Fix issue #100

### CODE REVIEW

**Comment by lihbr** [comment]
Thank you so much @tosbatti! I'll check that out soon and try to publish a patch before the end of the week ☺️

**Comment by tosbatti** [comment]
Hi @lihbr, I tried to do the fix but I broke the tests 😅
I moved `app` definition, because it was needed also before.
Sorry, I suppose the problem is quite simple, but I can't figure out which is.

**Comment by lihbr** [comment]
Thank you so much @tosbatti! I'll check that out soon and try to publish a patch before the end of the week ☺️

I'll check for the test also 😉

**Comment by tosbatti** [comment]
@lihbr, I found the problem!!! An additional mock was needed for `fs.existsSync`, as I added a new call.

**Review by lihbr — APPROVED** [review]
Works like a charm now 👌

**Pull request merged**
